### ISSUE TITLE
incorporate transit in targets

### ISSUE THREAD

**Issue by temospena** [U-Shift/SiteSelection#11]

**Comment by temospena** [comment]
make freq values as variable. example:
`freq_bus = c(4, 10, 20)`

**Comment by temospena** [comment]
done.
but we should test with a place with no bus stops (eg. Entroncamento).
the ifelse statment with` !is.null()` is not working properly. 
Maybe find a way to put this `ifelse` when filtering the points (upstream)

leaving open for now.

**Comment by temospena** [comment]
use different values as a threshold for bus frequency?
for instance, based on the actual frequency values detected, such as P75?
@valenca13

**Comment by valenca13** [comment]
Put transit as not an excluding criteria. Therefore. If all other criteria meet (complex space). If all others and PT meet (very complex). 
THere should be a classification like 1- complex and 2-very complex. @temospena

**Comment by temospena** [comment]
![image](https://github.com/U-Shift/SiteSelection/assets/39107166/67395f6e-d986-47f9-bfd3-dd1d461b14a6)
@valenca13
