### ISSUE TITLE
GTFS filter trips in a given date

### ISSUE THREAD

**Issue by temospena** [U-Shift/SiteSelection#9]
The function `tidytransit::filter_feed_by_date()` retrieves all the services that run in that date but that also sun in other dates.
This is not what we want.

Another option is to identify which **service pattern** has more days, trips and routes, and filter that `service_id`.

Here is how:
https://cran.r-project.org/web/packages/tidytransit/vignettes/frequency.html

**Comment by valenca13** [comment]
![braga](https://github.com/U-Shift/SiteSelection/assets/69808511/3e386d36-ad1f-490d-9656-a8ff37356448)

Here are the Results for Braga

**Comment by valenca13** [comment]
![lisbon](https://github.com/U-Shift/SiteSelection/assets/69808511/ae35a94b-5d5b-433c-8570-ec34001ffad9)

AML has 188 service patterns. We can choose the ones that operate during more days the year. Calendar dates from AML range from 01/07/2023 to 31/12/2024.

**Comment by temospena** [comment]
Can you choose more than one?

**Comment by valenca13** [comment]
Analyze the service patterns of AML. Take a look at the locations.

**Comment by valenca13** [comment]
![aml](https://github.com/U-Shift/SiteSelection/assets/69808511/26acbbd5-dabe-4f9c-b6a1-bfe2326bc97f)

All the bus stops that are present in the AML. Check the locations of the most frequent service patterns. Are they in different locations?

**Comment by valenca13** [comment]
![service_pattern_2](https://github.com/U-Shift/SiteSelection/assets/69808511/53c06b32-0d6c-4b4a-a989-757d079ca69f)

Bus routes of service pattern "s_0973a74" (191 days)

**Comment by valenca13** [comment]
![service_pattern_3](https://github.com/U-Shift/SiteSelection/assets/69808511/b7af6da8-eb74-4ac1-a7cc-8efd687640d7)

Bus routes of service patterns "s_70dfe23" (188 days)

**Comment by valenca13** [comment]
The most frequent service patterns are actually in different locations in the AML. Should we aggregate the 3? What are the next steps? @temospena

**Comment by temospena** [comment]
I would expect that. But there should be 4 expressive service patterns, not 3, 1 for each area.
After finding this 4th one, I would suggest to change the calendar dates of the less expressive ones, to be compatible with the most expressive one.
For instance, if service_pattern 3 is running between 01-01-2024 to 31-03-2024 and service_pattern 1 is running between 01-10-2023 to 31-12-2023, recode the calendar dates of this one to be at same date and time than the previous one (looking at the calendar and matching monday with monday)

**Comment by valenca13** [comment]
![service_pattern_7](https://github.com/U-Shift/SiteSelection/assets/69808511/91d02761-3717-41db-a0e7-902d579e3352)

This is the service pattern with that operates in 7th most days of the year ("s_a6bf59d (44 days)). The other 3 service patterns are very similar to the ones that I have already got.

**Comment by valenca13** [comment]
![service_pattern_11](https://github.com/U-Shift/SiteSelection/assets/69808511/56a269fa-dc06-4cb2-bc11-20465c3ff06e)
Service pattern 11 seems to be the fourth region ("s_fff1bcb" (39 days))

**Comment by valenca13** [comment]
![service_pattern_12](https://github.com/U-Shift/SiteSelection/assets/69808511/3e6fe559-3da3-42da-92e1-63cb368c0e25)
Also service pattern 12 (""s_fff1bcb" (39 days))

**Comment by valenca13** [comment]
> > Service pattern 11 seems to be the fourth region ("s_f22b75f" (39 days)). @temospena
> 
> There should be a service pattern going south, to Montijo, Alcochete, and so on...

![service_pattern_18](https://github.com/U-Shift/SiteSelection/assets/69808511/613baedb-2ba2-4a7e-bce1-6b956d26bf2f)

Service_pattern "s_bc376dc" (37 days)

**Comment by valenca13** [comment]
Adopted service patterns (ranked by "days in service"): 

1. Service pattern #1: "s_d38ffee" (192 days)
2. Service pattern #2: "s_0973a74" (191 days)
3. Service pattern #3: "s_70dfe23" (188 days)
4. Service pattern #12: "s_fff1bcb" (39 days)
5. Service pattern #18: "s_bc376dc" (37 days)

**Comment by valenca13** [comment]
> 5\. "s_bc376dc"

![Captura de ecrã 2024-04-30 111946](https://github.com/U-Shift/SiteSelection/assets/69808511/61cd10c3-94dc-40c9-9ee6-e27d7815c59d)

O service pattern 18 só opera 1 mês. Vou ter que analisar os próximos passos.

**Comment by valenca13** [comment]
- Filtrar por essa data (e.g., 10 de abril 2024) para cada servicepattern_id. 
- Calcular o numero de frequencias por cada paragem depois juntar todas tabelas em uma só.

**Comment by valenca13** [comment]
- Lisboa está dando erro. Não acha dados. 
- Juntar dados com rbind
- Fazer o piggyback para colocar os dados (geopackage) no release

**Comment by valenca13** [comment]
Critérios: 

- Classificar a frequência por hora nos níveis de serviço (1-4), baseados nos critérios da foto. 
- Calcular o nível de serviço máximo ao decorrer de todas as horas. 
- Critério de inclusão: Nivel de serviço máximo 3 ou 4. 

@temospena 
![Captura de ecrã 2024-05-05 130336](https://github.com/U-Shift/SiteSelection/assets/69808511/f779d775-b877-4ff6-84af-086c3c428f09)

**Comment by valenca13** [comment]
@temospena Já fiz o código dos níveis de serviço dentro da célula no código "cellcandidates.R". Por favor verifique se está tudo ok. Obrigado.

**Comment by temospena** [comment]
The file was generated for Portugal (great work @valenca13 !) and is available at releases.

The code is not fully reproducible because `tidytransit](tidytransit::set_servicepattern()` generates random hash numbers for identificators.

Something to consider when rebuilding for other year/region.
